import {StyleSheet} from 'react-native';
import Signup from './Signup';
import {Dimensions} from 'react-native';

const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  Start: {
    backgroundColor: 'white',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Login: {
    flex: 1,
    backgroundColor: '#FFFFF',
    padding: 20,
  },
  Signup: {
    backgroundColor: 'white',
    flex: 1,
  },

  Home: {
    flex: 1,
    backgroundColor: '#E6BCCD',
    padding: 20,
    justifyContent: 'center',
  },
  input: {
    height: 50,
    borderColor: '#',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    backgroundColor: '#E6BCCD',
    marginBottom: 20,
    fontSize: 16,
  },
  heading: {
    color: '#202020',
    fontSize: 52,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    padding: 20,
  },
  button: {
    backgroundColor: '#004CFF',
    padding: 20,
    height: 70,
    width: 350,
    borderRadius: 30,
    alignItems: 'center',
    position: 'absolute',
    bottom: 60,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
  },
  logo: {
    backgroundColor: '#FFFFFF',
    padding: 1,
    height: 200,
    width: 200,
    borderRadius: 200 / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo1: {
    flex: 0.48,
  },
  text: {
    fontSize: 19,
    fontWeight: 'light',
    color: '#202020',
  },
  bottomView: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  button2: {
    backgroundColor: '#004CFF',
    padding: 10,
    height: 36,
    width: 36,
    borderRadius: 18,
    alignItems: 'center',
    position: 'absolute',
    bottom: 10,
  },
  backgroundImage: {
    flex: 1,
    width: 410,
    height: 300,
    position: 'absolute',
    top: 1,
  },
  Emailbutton: {
    backgroundColor: '#DBEBFA',
    padding: 20,
    width: 325,
    borderRadius: 50,
  },
  backgroundImage2: {
    flex: 1,
  },
  backgroundImage3: {
    flex: 1,
    width: 410,
    height: 300,
    position: 'absolute',
    top: 1,
  },
  logo3: {
    backgroundColor: '#FFFFFF',
    padding: 1,
    height: 150,
    width: 150,
    borderRadius: 150 / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo5: {
    height: 130,
    width: 130,
    borderRadius: 130 / 2,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    backgroundColor: '#',
    borderColor: '#AB1234',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginBottom: 20,
    backgroundColor: '#004CFF',
  },
  optionBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    width: 300,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
  },

  selectedBox: {
    borderColor: '#4e9bde',
    backgroundColor: '#e6f2fb',
  },

  radioCircle: {
    height: 24,
    width: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#4e9bde',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  optionText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 16,
  },

  selectedCircle: {
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: '#4e9bde',
  },
  OTP: {
    borderWidth: 1,
    borderColor: '#CCC',
    backgroundColor: '#54C6EB',
    borderRadius: 25,
    width: 50,
    height: 50,
    margin: 5,
    textAlign: 'center',
    fontSize: 20,
  },
  sendagainbutton: {
    backgroundColor: '#FF5790',
    padding: 20,
    height: 70,
    width: '60%',
    borderRadius: 30,
    alignItems: 'center',
    position: 'absolute',
    bottom: 60,
  },
  newpasswordTextBox: {
    flex: 1,
    backgroundColor: '#DCDCDC',
    padding: 20,
    height: 70,
    width: '80%',
    borderRadius: 30,
    alignItems: 'center',
    position: 'absolute',
  },
  searchbox: {
    flex: 1,
    backgroundColor: '#C7C7C7',
    padding: 15,
    height: 50,
    width: 50,
    borderRadius: 50,
    alignItems: 'center',
  },
  profileCircle: {
    height: 50,
    width: 50,
    borderRadius: 25,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 30,
    backgroundColor: '#FFFFFF',
  },
  profilePic: {
    height: 40,
    width: 40,
    borderRadius: 20,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ViewPic: {
    height: 50,
    width: 50,
    borderRadius: 25,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewCircle: {
    height: 60,
    width: 60,
    borderRadius: 30,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  ViewStories: {
    height: height * 0.2156,
    width: width * 0.2773,
    borderRadius: 30,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  NewItemViewbox: {
    height: height * 0.1848,
    width: width * 0.4,
    borderRadius: 9,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  NewItemImage: {
    height: height * 0.1601,
    width: width * 0.3466,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },

  modalBackground: {
    flex: 1,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeArea: {
    alignItems: 'center',
  },
  fullImage: {
    width: 300,
    height: 450,
    borderRadius: 8,
  },
  closeText1: {
    color: '#FFFFFF',
    marginTop: 12,
    fontSize: 16,
  },
  MostPopularImage: {
    height: height * 0.1601,
    width: width * 0.3466,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    //marginRight : 20,
    //marginTop : 10,
    //marginBottom : 10
  },
  MostPopularView: {
    height: height * 0.1901,
    width: width * 0.3666,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
    marginTop: 20,
    marginBottom: 20,
  },
  largeImage: {
    width: 300,
    height: 300,
    borderRadius: 10,
  },
  closeText: {
    color: 'black',
    marginTop: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#f8f8f8',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
